### PR TITLE
Add parser.

### PR DESCRIPTION
**Pull request by nythranix**

### CODE REVIEW

**Review by MMVahedi — CHANGES_REQUESTED** [review]
Great Job!
I have some comments:
- The leaves method name (in Parser class) is misspelled. 
- We need a method in the Node class that returns the text content of the tag to extract features. with this method, we can handle words_count and length in the feature class and it is better to move this method to the feature class. For now, just add the get_text_content method in Node Class, I will handle other things by myself.

Thanks.

**Review by ArmanL-Khani — CHANGES_REQUESTED** [review]
Also remove tags: navigation, anchor (a), button, link .Consider removing section tag as well. Use str.replace(" ","") and other similar functions to remove empty spaces in the TODO part. Extract h1 and title like the description (It is best practice that web developers use h1 only once, but get the first instance for reliability)

**Comment by nythranix** [comment]
> Great Job! I have some comments:
> 
> * The leaves method name (in Parser class) is misspelled.
> * We need a method in the Node class that returns the text content of the tag to extract features. with this method, we can handle words_count and length in the feature class and it is better to move this method to the feature class. For now, just add the get_text_content method in Node Class, I will handle other things by myself.
> 
> Thanks.

Fixed

**Review by MMVahedi — APPROVED** [review]

**Review by ArmanL-Khani — CHANGES_REQUESTED** [review]
My previous issues are still not addressed

**Comment by nythranix** [comment]
> My previous issues are still not addressed

- We need to have a discussion about our approach to cleaning the HTML pages. The code is ready but rushing to remove tags and their content might cause further issues.
- title method is added in the last commit.

**Review by ArmanL-Khani — APPROVED** [review]
For the moment, I approve this but we need further discussions about html cleaning

**Pull request merged**
